version: "3"
services:
    www:
        image: web-server
        ports: 
            - "8000:80"
        links:
            - db
        networks:
            - default
        restart: always
    db:
        image: sql-server
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: sqlitraining
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./udf:/usr/lib/mysql/plugin
            - persistent:/var/lib/mysql
        networks:
            - default
        restart: always
volumes:
    persistent: